## ------------------------------------------
## APPLICATION INFO
## ------------------------------------------
#spring.application.name=drivingschool
#server.port=8080
#
## ------------------------------------------
## DATASOURCE (MySQL)
## ------------------------------------------
#spring.datasource.url= ${MYSQL_URL}
#spring.datasource.username=${MYSQL_USER}
#spring.datasource.password=${MYSQL_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
#whatsapp.phone.number.id=${WHATSAPP_PHONE_NUMBER_ID}
#whatsapp.token=${WHATSAPP_ACCESS_TOKEN}
#whatsapp.api.url=https://graph.facebook.com/v20.0/
## ------------------------------------------
## JPA / HIBERNATE
## ------------------------------------------
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
## ------------------------------------------
## JWT CONFIGURATION
## ------------------------------------------
#jwt.secret=${JWT_SECRET}
#jwt.expiration-ms=${JWT_EXPIRATION}
#
#
## ------------------------------------------
## OPTIONAL EXTERNAL API
## ------------------------------------------
#ors.api.key=${ORS_API_KEY}
#
#
#
## ------------------------------------------
## LOGGING
## ------------------------------------------
#logging.level.org.springframework.security=INFO
#logging.level.com.example=DEBUG



# ------------------------------------------
# APPLICATION INFO
# ------------------------------------------
spring.application.name=drivingschool
server.port=8080

# ------------------------------------------
# DATASOURCE (MySQL)
# ------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/driving_school?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


whatsapp.phone.number.id=912720908587996
whatsapp.token=EAAQLZA2Y85ZBEBQcJV5ZCzSii18StSFu7wP51uEmU4NrBRFMI2I9xFrqHaZBQRAkUcsIF8Dnrl87OECwXvUtW7jtPKicl0qLastnLcYs4niie8ELY1I05Gy2HvHNekGvsZCbbY9v2OzuRP45rZCQthwPlH1QZAxU4UjtfHZAcDPZBcUIky5A83wUCCXjHktEiPWjL6r5rDc0a3GmuNA8gtG8mwDgMh8ZAZCgKZA9bj61X7LUAx4ZBZBeB4nkVJZAWq97mrjXt0lv9jHXrJsTcjvROQNWBEq63dj
whatsapp.api.url=https://graph.facebook.com/v20.0/
# ------------------------------------------
# JPA / HIBERNATE
# ------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ------------------------------------------
# JWT CONFIGURATION
# ------------------------------------------
jwt.secret=V8N7zA3yPq9Rt6BvX1u2Kc5Jm8Lh0Ds4Ew9Qp6Tz7Rr3Yf2Nq5Uo8Ia7Wc4Lp9Jx
jwt.expiration-ms=86400000


ors.api.key = eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImNiNjJjMDBmMGNmOTRjMTM5YTBmYTA2NGI2MTVjZWIzIiwiaCI6Im11cm11cjY0In0=



# ------------------------------------------
# LOGGING
# ------------------------------------------
logging.level.org.springframework.security=INFO
logging.level.com.example=DEBUG
